"""empty message

Revision ID: 95820145a301
Revises: e72c1c3f47e1
Create Date: 2022-01-28 11:27:34.147737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95820145a301'
down_revision = 'e72c1c3f47e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_author', sa.Text(length=500), nullable=True))
    op.add_column('users', sa.Column('profile_pic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'about_author')
    # ### end Alembic commands ###
